/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tallerreparacioncelular.JFames;

import com.mycompany.tallerreparacioncelular.Controlador.EquipoControlador;
import com.mycompany.tallerreparacioncelular.entidades.EquipoEntidad;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 * @author Lady
 */
public class Equipo extends javax.swing.JPanel {

    private final EquipoControlador controlador = new EquipoControlador();
    private DefaultTableModel modeloTabla;

    public Equipo() {
        initComponents();
        configurarTabla();
        cargarTabla(controlador.listarTodos());
    }
    
    /** columnas de la JTable */
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Marca", "Modelo", "IMEI", "Falla", "Accesorios"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // No permitir editar directamente en la tabla
                return false;
            }
        };

        TablaEquipo.setModel(modeloTabla);
    }

    /** Carga una lista de equipos en la tabla */
    private void cargarTabla(List<EquipoEntidad> lista) {
        modeloTabla.setRowCount(0);

        for (EquipoEntidad e : lista) {
            modeloTabla.addRow(new Object[]{
                e.getIdInterno(),
                e.getMarca(),
                e.getModelo(),
                e.getImei(),
                e.getFallaReportada(),
                e.getAccesoriosEntregados()
            });
        }
    }

    /** Construye un objeto EquipoEntidad con lo que hay en el formulario */
    private EquipoEntidad construirDesdeFormulario() {
        String id = txtIdInterno.getText().trim();
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        String imei = txtImei.getText().trim();
        String falla = txtFalla.getText().trim();
        String accesorios = txtAccesorios.getText().trim();

        // Si el ID está vacío, generamos uno sencillo basado en la cantidad de filas
        if (id.isEmpty()) {
            id = String.valueOf(modeloTabla.getRowCount() + 1);
        }

        return new EquipoEntidad(
                id,
                marca,
                modelo,
                imei,
                falla,
                accesorios
        );
    }

    /** Limpia todos los campos del formulario */
    private void limpiarCampos() {
        txtIdInterno.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtImei.setText("");
        txtFalla.setText("");
        txtAccesorios.setText("");
        TablaEquipo.clearSelection();
    }

    /** Rellena el formulario con los datos de la fila seleccionada en la tabla */
    private void rellenarFormularioDesdeTabla() {
        int fila = TablaEquipo.getSelectedRow();
        if (fila == -1) {
            return;
        }

        txtIdInterno.setText(String.valueOf(TablaEquipo.getValueAt(fila, 0)));
        txtMarca.setText(String.valueOf(TablaEquipo.getValueAt(fila, 1)));
        txtModelo.setText(String.valueOf(TablaEquipo.getValueAt(fila, 2)));
        txtImei.setText(String.valueOf(TablaEquipo.getValueAt(fila, 3)));
        txtFalla.setText(String.valueOf(TablaEquipo.getValueAt(fila, 4)));
        txtAccesorios.setText(String.valueOf(TablaEquipo.getValueAt(fila, 5)));
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDinterno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdInterno = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtImei = new javax.swing.JTextField();
        txtFalla = new javax.swing.JTextField();
        txtAccesorios = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEquipo = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnBuscarImei = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 586));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("PANEL DE EQUIPOS");

        txtIDinterno.setText("ID interno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Marca:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("IMEI:");

        jLabel5.setText("Falla reportada:");

        jLabel6.setText("Accesorios entregados:");

        TablaEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaEquipo);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscarImei.setText("Buscar por IMEI");
        btnBuscarImei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImeiActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDinterno)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImei, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFalla, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarImei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addGap(12, 12, 12)
                        .addComponent(btnCerrar)))
                .addContainerGap(749, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDinterno)
                    .addComponent(txtIdInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtImei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtFalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBuscarImei)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addGap(351, 351, 351))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String imei = txtImei.getText().trim();

        if (imei.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Ingrese el IMEI del equipo a eliminar o búsquelo primero.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que desea eliminar el equipo con IMEI " + imei + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            controlador.eliminarPorImei(imei);
            cargarTabla(controlador.listarTodos());
            limpiarCampos();

            JOptionPane.showMessageDialog(
                this,
                "Equipo eliminado correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        
    }//GEN-LAST:event_btnEliminarActionPerformed
}
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = TablaEquipo.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Primero selecciona un equipo en la tabla.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String imeiOriginal = String.valueOf(TablaEquipo.getValueAt(fila, 3)); // columna IMEI

        try {
            EquipoEntidad datosNuevos = construirDesdeFormulario();
            controlador.actualizar(imeiOriginal, datosNuevos);

            cargarTabla(controlador.listarTodos());
            limpiarCampos();

            JOptionPane.showMessageDialog(
                this,
                "Equipo actualizado correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarImeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImeiActionPerformed
        String imeiBuscado = txtImei.getText().trim();

        if (imeiBuscado.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Escribe un IMEI en el campo correspondiente.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        EquipoEntidad encontrado = controlador.buscarPorImei(imeiBuscado);

        if (encontrado == null) {
            JOptionPane.showMessageDialog(
                this,
                "No se encontró ningún equipo con ese IMEI.",
                "Sin resultados",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        // Rellena el formulario
        txtIdInterno.setText(encontrado.getIdInterno());
        txtMarca.setText(encontrado.getMarca());
        txtModelo.setText(encontrado.getModelo());
        txtImei.setText(encontrado.getImei());
        txtFalla.setText(encontrado.getFallaReportada());
        txtAccesorios.setText(encontrado.getAccesoriosEntregados());

        // Selecciona la fila correspondiente en la tabla (si existe)
        for (int i = 0; i < TablaEquipo.getRowCount(); i++) {
            String imeiTabla = String.valueOf(TablaEquipo.getValueAt(i, 3));
            if (imeiTabla.equals(encontrado.getImei())) {
                TablaEquipo.setRowSelectionInterval(i, i);
                break;
            }
        }

    }//GEN-LAST:event_btnBuscarImeiActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            EquipoEntidad nuevo = construirDesdeFormulario();
            controlador.registrar(nuevo);

            cargarTabla(controlador.listarTodos());
            limpiarCampos();

            JOptionPane.showMessageDialog(
                this,
                "Equipo registrado correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEquipo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarImei;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAccesorios;
    private javax.swing.JTextField txtFalla;
    private javax.swing.JLabel txtIDinterno;
    private javax.swing.JTextField txtIdInterno;
    private javax.swing.JTextField txtImei;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
